// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type CageCard struct {
	CcID         int32
	Activated    sql.NullTime
	Deactivated  sql.NullTime
	Investigator string
}
