// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settings.sql

package database

import (
	"context"
)

const activateSelfOnly = `-- name: ActivateSelfOnly :one
SELECT only_activate_self FROM settings
`

func (q *Queries) ActivateSelfOnly(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, activateSelfOnly)
	var only_activate_self bool
	err := row.Scan(&only_activate_self)
	return only_activate_self, err
}

const firstTimeSetupComplete = `-- name: FirstTimeSetupComplete :exec
UPDATE settings SET settings_complete = true
`

func (q *Queries) FirstTimeSetupComplete(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, firstTimeSetupComplete)
	return err
}

const getSettings = `-- name: GetSettings :one
SELECT id, settings_complete, only_activate_self, test_data_loaded FROM settings
WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SettingsComplete,
		&i.OnlyActivateSelf,
		&i.TestDataLoaded,
	)
	return i, err
}

const setUpSettings = `-- name: SetUpSettings :exec

INSERT INTO settings(id, settings_complete, only_activate_self, test_data_loaded)
VALUES (1, false, false, false)
`

// settings is saving the settings. this should ONLY ever have one row
func (q *Queries) SetUpSettings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, setUpSettings)
	return err
}

const testDataLoaded = `-- name: TestDataLoaded :exec
UPDATE settings SET test_data_loaded = true
`

func (q *Queries) TestDataLoaded(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, testDataLoaded)
	return err
}

const updateActivateSelf = `-- name: UpdateActivateSelf :exec
UPDATE settings SET only_activate_self = $1
`

func (q *Queries) UpdateActivateSelf(ctx context.Context, onlyActivateSelf bool) error {
	_, err := q.db.ExecContext(ctx, updateActivateSelf, onlyActivateSelf)
	return err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings
SET only_activate_self = $1
`

func (q *Queries) UpdateSettings(ctx context.Context, onlyActivateSelf bool) error {
	_, err := q.db.ExecContext(ctx, updateSettings, onlyActivateSelf)
	return err
}
