// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: testing.sql

package database

import (
	"context"
)

const resetDatabase = `-- name: ResetDatabase :exec
TRUNCATE cage_cards, 
    strains, 
    added_to_protocol, 
    investigators, 
    positions, 
    settings CASCADE
`

func (q *Queries) ResetDatabase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDatabase)
	return err
}
